language: node_js

addons:
  postgresql: "9.1"

before_script:
  - psql --version
  - cp test/postgres/knexfile.js.dist test/postgres/knexfile.js
  - cp test/sqlite/knexfile.js.dist test/sqlite/knexfile.js
  - psql -U postgres -c 'create database "bookshelf-json-columns";'

node_js:
  - "0.10"
  - "4"
  - "5"

after_success:
  - npm run coveralls

sudo: false
